# 线性代数

## 降维

我们对于矩阵的降维通常称为“求和”。其实就是对于行或列进行求和。

In [3]:
import torch

x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

上面我们成功把一个一维的 tensor 将为零维哈哈。

当然，我们也可以对行或列进行求和，只需要指定轴即可：

In [8]:
A = torch.arange(16, dtype=torch.float32).reshape(4, -1)

A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
A, A_sum_axis0, A_sum_axis1, A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([24., 28., 32., 36.]),
 tensor([ 6., 22., 38., 54.]),
 torch.Size([4]))

所以，对于求和：

- `axis=0` 就是对每一列求和
- `axis=1` 就是对每一行求和

这个轴和上一节提到的删除 Pandas 中的行/列代指的有所不同

## 矩阵的一些量

### 均值

In [9]:
A.mean(), A.sum() / A.numel() # 二者等价

(tensor(7.5000), tensor(7.5000))

也可以沿着行或列求平均值：

In [11]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]  # 二者等价。对每一列求均值

(tensor([6., 7., 8., 9.]), tensor([6., 7., 8., 9.]))

## 非降维求和

我们也可以在不降低维度（不改变 `tensor` 尺寸的情况下求和）：

In [13]:
sum_A_0 = A.sum(axis=0, keepdim=True)
sum_A_1 = A.sum(axis=1, keepdim=True)
sum_A_0, sum_A_1

(tensor([[24., 28., 32., 36.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.]]))

对吧，没有改变尺寸。

然后，我们还可以求一个 cumulative sum 累计求和。可以从小的矩阵看出端倪这是啥：

In [15]:
aa = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.cumsum(aa, axis=0), torch.cumsum(aa, axis=1)

(tensor([[1, 2, 3],
         [5, 7, 9]]),
 tensor([[ 1,  3,  6],
         [ 4,  9, 15]]))

对列求 `cumsum` 的时候：

- 第一行：`1=1`, `2=2`, `3=3`
- 第二行：`5=1+4`, `7=2+5`, `9=3+6`

对行求得时候：

- 第一列：`1=1`, `4=4`
- 第二列：`3=1+2`, `9=4+5`
- 第三列：`6=1+2+3`, `15=4+5+6`

## 范数

简介：[范数](https://zh-v2.d2l.ai/chapter_preliminaries/linear-algebra.html#subsec-lin-algebra-norms)

### $L_2$ 范数

$L_2$ 范数其实就是常叫的**向量的模**，也就是所有向量的分量的平方和的平方根：

$$
\|\mathbf{x}\|_2=\sqrt{\sum_{i=1}^n x_i^2}
$$

In [16]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

### $L_1$ 范数

$L_1$ 范数是所有元素的绝对值之和：

$$
\|\mathbf{x}\|_1=\sum_{i=1}^n \left| x \right|
$$

In [17]:
torch.abs(u).sum()

tensor(7.)

### 一般范数形式 $L_p$

$$
\|\mathbf{x}\|_p=\left(\sum_{i=1}^n\left|x_i\right|^p\right)^{1 / p}
$$

### 矩阵的 $L_2$ 范数

类似于向量的 $L_2$ 范数，矩阵有一个 *Frobenius* 范数：

$$
\| \mathbf{X} \|_F = \sqrt{ \sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}
$$

In [20]:
bb = torch.ones(4, 9)
torch.norm(bb)

tensor(6.)

## 练习

算了